server:
  port: 8010

user:
                  #http://localhost:7900/simple/
  userServicePath: http://microservice-provider-user/simple/

spring:
  application:
    name: microservice-consumer-movie-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}


microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900